/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/atoms/WButtom copy.vue')['default']
    DownloadButtom: typeof import('./src/components/atoms/DownloadButtom.vue')['default']
    PopOut: typeof import('./src/components/atoms/popOut.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WButtom: typeof import('./src/components/atoms/WButtom.vue')['default']
    WLine: typeof import('./src/components/atoms/WLine.vue')['default']
  }
}
